apiVersion: 1

datasources:
  - name: AlarmState
    type: elasticsearch
    access: proxy
    database: "heartofgold_alarms_state_*"
    url: http://elasticsearch:9200
    jsonData:
      esVersion: 60
      timeField: "time"
      logMessageField: "_id"
